@echo off
REM SpaceX Tracker - Release Build Script
REM Generated by Nexus Platform - Día 10
REM Uso: build-release.bat [clean|build|bundle|all]

echo 🚀 SpaceX Tracker - Release Build Script
echo ====================================
echo.

set ACTION=%1
if "%ACTION%"=="" set ACTION=all

if "%ACTION%"=="clean" goto clean
if "%ACTION%"=="build" goto build
if "%ACTION%"=="bundle" goto bundle
if "%ACTION%"=="all" goto all

:clean
echo 🧹 Limpiando proyecto...
call gradlew clean
echo ✅ Limpieza completada
goto end

:build
echo 📱 Generando APK Release...
call gradlew assembleRelease
echo ✅ APK generado: app\build\outputs\apk\release\app-release.apk
goto end

:bundle
echo 📦 Generando Android App Bundle (AAB)...
call gradlew bundleRelease
echo ✅ Bundle generado: app\build\outputs\bundle\release\app-release.aab
goto end

:all
echo 🚀 BUILD COMPLETO - Generando APK y Bundle...
echo.
call gradlew clean
echo 1/3 ✅ Proyecto limpio
echo.
call gradlew assembleRelease
echo 2/3 ✅ APK Release generado
echo.
call gradlew bundleRelease
echo 3/3 ✅ Bundle AAB generado
echo.
echo 🎉 BUILD COMPLETADO
echo.
echo 📁 Archivos generados:
echo    - APK: app\build\outputs\apk\release\app-release.apk
echo    - AAB: app\build\outputs\bundle\release\app-release.aab
echo.
echo 📤 Listo para subir a Play Store (usa el archivo .aab)
goto end

:end
echo.
echo 🔗 Más info: https://github.com/Martineto21/nexus-lab-spacex-tracker
echo 🧠 Generado por Nexus Platform - app.kalmiazen.com
pause